AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Weather Batch Lambda Function - Fetch weather charts from JMA

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        PDF_URLS_00: https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa252_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa302_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa402_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa502_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe5782_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe5784_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe577_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe502_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe504_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe507_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa20_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa25_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupn30_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq35_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq78_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axfe578_00.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axjp140_00.pdf
        PDF_URLS_12: https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa252_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa302_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa402_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fupa502_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe5782_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe5784_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe577_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe502_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe504_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/fxfe507_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa20_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupa25_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupn30_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq35_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/aupq78_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axfe578_12.pdf,
          https://www.jma.go.jp/bosai/numericmap/data/nwpmap/axjp140_12.pdf
        S3_PREFIX: pdfs/
        S3_METADATA_KEY: pdfs/metadata.json

Parameters:
  S3BucketName:
    Type: String
    Default: weather-batch-pdfs
    Description: S3 bucket name for storing PDFs
  
  Schedule00UTC:
    Type: String
    Default: cron(30 1 * * ? *)
    Description: Schedule expression for 00 UTC execution

  Schedule12UTC:
    Type: String
    Default: cron(30 13 * * ? *)
    Description: Schedule expression for 12 UTC execution

Resources:
  # Lambda Function
  WeatherBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: weather-batch
      Handler: com.example.pdfbatch.lambda.LambdaHandler::handleRequest
      CodeUri: build/distributions/weather-batch.zip
      Description: Fetch weather charts from JMA and store to S3
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
      Events:
        Schedule00UTC:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule00UTC
            Description: PDF fetch at 00 UTC
            Enabled: true
            Input: '{"timeSlot": "00"}'
        Schedule12UTC:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule12UTC
            Description: PDF fetch at 12 UTC
            Enabled: true
            Input: '{"timeSlot": "12"}'

  # S3 Bucket
  WeatherBatchBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # CloudWatch Log Group
  WeatherBatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WeatherBatchFunction}
      RetentionInDays: 30

Outputs:
  WeatherBatchFunctionArn:
    Description: Weather Batch Lambda Function ARN
    Value: !GetAtt WeatherBatchFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn
  
  WeatherBatchBucketName:
    Description: S3 Bucket Name
    Value: !Ref WeatherBatchBucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName
  
  Schedule00UTC:
    Description: Schedule Expression for 00 UTC
    Value: !Ref Schedule00UTC

  Schedule12UTC:
    Description: Schedule Expression for 12 UTC
    Value: !Ref Schedule12UTC
